# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "precise64"

  config.vm.network :private_network, ip: "192.168.33.10"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "cookbooks/"
    chef.add_recipe "concrete5base"
    chef.json = {
   	    "mysql" => {
   		"server_debian_password" => "0000",
   		"server_root_password" => "0000",
   		"server_repl_password" => "0000",
   	    	"bind_address" => "127.0.0.1"
   	    },
   	    "db" => {
        	"dev" => "concrete5base"
   	    }
	}
  end
  
  config.vm.synced_folder "../app/", "/var/www", owner: "vagrant", group: "www-data"
  
end